protein = "MNTQCTNYEAVSPKLGCTDWWGENTKQEGWCFVRGRIDHCQFRGKWEIEQSDGDPKSGTPNWIVPTTMSRCSMRDQMPAPPGVQHLQWWAQQSWWGHITGAEDNVKHMCFSGIPGLNGGMKYNFQMPHQTNPRYEEFTVGIRSERTHPQVFIDKFYETSNAIQKNQAVHWYCVLGDTYDMGWDAIYEIAQSARFEPIENENGDMLMVAWQEQRQISWQALSVYFDWTPPYGNYMPEMCIPIENQMMKPSWCLGPNHMLVEEEDYRWAEDTTCKMAMMELPIPLPFNQNQEGHRTAGNQMLAIWQLGHMSYALCLDTSKVSNQQSEWKYKYFSMQKDLRLNCLEWFQSYCKQPNAQACGKNLQLDYVFVWTSNRQIFEMIFTCSSIKVKFETFKCSHWRYAWCQTHECFTSHCDHDMCADGNEDMSDMWNWSMENDAGTWLAMWKAINNFTSHMDTPPLMLTEFSGEARTWFCMENDLHLSNNNEYTDMFQNEDKNAFMGIMNWTWCPCVFKWEGYYMKQQYTWRRQNYYYAFEGSEELNEHKWPHVYHYMLMQHNDLLHTLVNMELVKCPGTLTTPDHDYYEQDRIMGMHTWAELCAYWTGRGETFQQFTVNGATVFYEYKFCPEWEFQLKHNMWWYVNGVNLYHHWPGDPKAGKFCPIPRILRLIMWCKSLLKSWFLIHLEQLKRPYRSMHYAARGWKLQHSKCRSSHCDEQDMHNDASDWICEGVPQYQTMIWQPDTCEMDPGVFGIACCDMEQRFMMDPIAMEKDCPEDDVVRITAPIDDQLALYWQQCWHWIDNDRWIHTHEYLMDLVWTCLNVVVPALFCRRASLLEEHYYEYSVHPSDFRCYAVCPEYLDNKPFGQHNANEMFLRAHCRNTQGYPSFGMSTHFSKESQEWYAMLCCNPFSSSDPKHHEGAHLTVILSGRLSPRHPHGDVHFMTTWRWAPSAKVYRDLWCAGPKNKRRHEHVCQEGLMKFGCEHDQKPYDIHLCILQRMWCDVNI"
possible_proteins = 1

for aminoacid in protein:
    match aminoacid:
        case 'M'|'W':
            possible_proteins *= 1
        case 'H'|'N'|'Y'|'D'|'Q'|'E'|'F'|'C'|'K':
            possible_proteins *= 2
        case 'I':
            possible_proteins *= 3
        case 'T'|'G'|'P'|'A'|'V':
            possible_proteins *= 4
        case 'S'|'L'|'R':
            possible_proteins *= 6

possible_proteins *= 3
print(possible_proteins%1000000)